######################################################################
# Automatically generated by qmake (2.01a) ?? 4? 16 09:00:24 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QT += network
QT -= gui

# Input
HEADERS += pipe.h server.h
SOURCES += main.cpp pipe.cpp server.cpp
