/**
 * Autogenerated by Thrift Compiler (0.7.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef handler_CONSTANTS_H
#define handler_CONSTANTS_H

#include "handler_types.h"



class handlerConstants {
 public:
  handlerConstants();

};

extern const handlerConstants g_handler_constants;



#endif
