/**
 * Autogenerated by Thrift Compiler (0.7.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef HandlerService_H
#define HandlerService_H

#include <TProcessor.h>
#include "handler_types.h"



class HandlerServiceIf {
 public:
  virtual ~HandlerServiceIf() {}
  virtual void handlerRead(std::string& _return, const int32_t key) = 0;
};

class HandlerServiceNull : virtual public HandlerServiceIf {
 public:
  virtual ~HandlerServiceNull() {}
  void handlerRead(std::string& /* _return */, const int32_t /* key */) {
    return;
  }
};

typedef struct _HandlerService_handlerRead_args__isset {
  _HandlerService_handlerRead_args__isset() : key(false) {}
  bool key;
} _HandlerService_handlerRead_args__isset;

class HandlerService_handlerRead_args {
 public:

  HandlerService_handlerRead_args() : key(0) {
  }

  virtual ~HandlerService_handlerRead_args() throw() {}

  int32_t key;

  _HandlerService_handlerRead_args__isset __isset;

  void __set_key(const int32_t val) {
    key = val;
  }

  bool operator == (const HandlerService_handlerRead_args & rhs) const
  {
    if (!(key == rhs.key))
      return false;
    return true;
  }
  bool operator != (const HandlerService_handlerRead_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const HandlerService_handlerRead_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class HandlerService_handlerRead_pargs {
 public:


  virtual ~HandlerService_handlerRead_pargs() throw() {}

  const int32_t* key;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _HandlerService_handlerRead_result__isset {
  _HandlerService_handlerRead_result__isset() : success(false) {}
  bool success;
} _HandlerService_handlerRead_result__isset;

class HandlerService_handlerRead_result {
 public:

  HandlerService_handlerRead_result() : success("") {
  }

  virtual ~HandlerService_handlerRead_result() throw() {}

  std::string success;

  _HandlerService_handlerRead_result__isset __isset;

  void __set_success(const std::string& val) {
    success = val;
  }

  bool operator == (const HandlerService_handlerRead_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const HandlerService_handlerRead_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const HandlerService_handlerRead_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _HandlerService_handlerRead_presult__isset {
  _HandlerService_handlerRead_presult__isset() : success(false) {}
  bool success;
} _HandlerService_handlerRead_presult__isset;

class HandlerService_handlerRead_presult {
 public:


  virtual ~HandlerService_handlerRead_presult() throw() {}

  std::string* success;

  _HandlerService_handlerRead_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class HandlerServiceClient : virtual public HandlerServiceIf {
 public:
  HandlerServiceClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
    piprot_(prot),
    poprot_(prot) {
    iprot_ = prot.get();
    oprot_ = prot.get();
  }
  HandlerServiceClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :
    piprot_(iprot),
    poprot_(oprot) {
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void handlerRead(std::string& _return, const int32_t key);
  void send_handlerRead(const int32_t key);
  void recv_handlerRead(std::string& _return);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class HandlerServiceProcessor : virtual public ::apache::thrift::TProcessor {
 protected:
  boost::shared_ptr<HandlerServiceIf> iface_;
  virtual bool process_fn(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, std::string& fname, int32_t seqid, void* callContext);
 private:
  std::map<std::string, void (HandlerServiceProcessor::*)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*)> processMap_;
  void process_handlerRead(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  HandlerServiceProcessor(boost::shared_ptr<HandlerServiceIf> iface) :
    iface_(iface) {
    processMap_["handlerRead"] = &HandlerServiceProcessor::process_handlerRead;
  }

  virtual bool process(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot, void* callContext);
  virtual ~HandlerServiceProcessor() {}
};

class HandlerServiceMultiface : virtual public HandlerServiceIf {
 public:
  HandlerServiceMultiface(std::vector<boost::shared_ptr<HandlerServiceIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~HandlerServiceMultiface() {}
 protected:
  std::vector<boost::shared_ptr<HandlerServiceIf> > ifaces_;
  HandlerServiceMultiface() {}
  void add(boost::shared_ptr<HandlerServiceIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void handlerRead(std::string& _return, const int32_t key) {
    size_t sz = ifaces_.size();
    for (size_t i = 0; i < sz; ++i) {
      if (i == sz - 1) {
        ifaces_[i]->handlerRead(_return, key);
        return;
      } else {
        ifaces_[i]->handlerRead(_return, key);
      }
    }
  }

};



#endif
