/**
 * Autogenerated by Thrift Compiler (0.7.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "handler_constants.h"



const handlerConstants g_handler_constants;

handlerConstants::handlerConstants() {
}



